
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'd1',
    name: 'Chapman Zest',
    category: 'drink',
    price: 1500,
    description: 'Classic Nigerian cocktail mix with fruity undertones.',
    image: 'https://picsum.photos/400/600?random=1',
    details: ['Fruity', 'Ice Cold', 'Local Favorite'],
    inStock: true,
  },
  {
    id: 'd2',
    name: 'Zobo Supreme',
    category: 'drink',
    price: 1200,
    description: 'Hibiscus infused refreshing drink with ginger spice.',
    image: 'https://picsum.photos/400/600?random=2',
    details: ['Natural', 'Spicy', 'Vitamin C'],
    inStock: true,
  },
  {
    id: 'd3',
    name: 'Tigernut Splash',
    category: 'drink',
    price: 2000,
    description: 'Creamy tigernut milk served chilled.',
    image: 'https://picsum.photos/400/600?random=3',
    details: ['Dairy Free', 'Creamy', 'Nutritious'],
    inStock: false,
  },
  {
    id: 'v1',
    name: 'Lexus LX 600',
    category: 'vehicle',
    price: 350000,
    description: 'Luxury SUV for executive movement. Daily Rate.',
    image: 'https://picsum.photos/600/400?random=4',
    details: ['Bulletproof', 'Chauffeur', 'Escort Ready'],
    inStock: true,
  },
  {
    id: 'v2',
    name: 'Toyota Land Cruiser',
    category: 'vehicle',
    price: 250000,
    description: 'Rugged reliability meets comfort.',
    image: 'https://picsum.photos/600/400?random=5',
    details: ['V8 Engine', 'Leather Seats', 'Tinted'],
    inStock: true,
  },
  {
    id: 'v3',
    name: 'Mercedes G-Wagon',
    category: 'vehicle',
    price: 500000,
    description: 'The ultimate statement of power and luxury.',
    image: 'https://picsum.photos/600/400?random=6',
    details: ['AMG', 'Blacked Out', 'Premium Sound'],
    inStock: true,
  },
];
